// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5q8MpiKmYZMqnolzqUTmmjcIF6mwV96Q',
    appId: '1:1075315020441:web:2ab9d6f53ec9689f0a1e08',
    messagingSenderId: '1075315020441',
    projectId: 'high-on-flutter-hackathon-smec',
    authDomain: 'high-on-flutter-hackathon-smec.firebaseapp.com',
    storageBucket: 'high-on-flutter-hackathon-smec.firebasestorage.app',
    measurementId: 'G-QZ8Z6ZZK7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBCUMzXH3g6IJoGNvh-1pSqasaRRZKGQY',
    appId: '1:1075315020441:android:aebfa4c6c1fc1cc20a1e08',
    messagingSenderId: '1075315020441',
    projectId: 'high-on-flutter-hackathon-smec',
    storageBucket: 'high-on-flutter-hackathon-smec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiqB2BPWdWdDNTerf2JeVsK6F_topFP8I',
    appId: '1:1075315020441:ios:4f75d244fc96c6f30a1e08',
    messagingSenderId: '1075315020441',
    projectId: 'high-on-flutter-hackathon-smec',
    storageBucket: 'high-on-flutter-hackathon-smec.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiqB2BPWdWdDNTerf2JeVsK6F_topFP8I',
    appId: '1:1075315020441:ios:4f75d244fc96c6f30a1e08',
    messagingSenderId: '1075315020441',
    projectId: 'high-on-flutter-hackathon-smec',
    storageBucket: 'high-on-flutter-hackathon-smec.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5q8MpiKmYZMqnolzqUTmmjcIF6mwV96Q',
    appId: '1:1075315020441:web:6f402a981dbe73770a1e08',
    messagingSenderId: '1075315020441',
    projectId: 'high-on-flutter-hackathon-smec',
    authDomain: 'high-on-flutter-hackathon-smec.firebaseapp.com',
    storageBucket: 'high-on-flutter-hackathon-smec.firebasestorage.app',
    measurementId: 'G-050X23XH1Z',
  );
}
